server:
    port: 8081

info: 外面yml

logging:
    level:
        org:
            apache:
                tomcat:
                    util:
                        net:
                            NioEndpoint: info
#trace: true
#        org: debug