
server:
    port: 8080

spring:
    application:
        name: spring-data-rest
    datasource:
        username: springstudy
        password: springstudy
        url: jdbc:mysql://localhost:3306/springstudy?characterEncoding=utf8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver


    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: true
    data:
        jpa:
            repositories:
                enabled: true